projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/app/repository/amplify/graphql/**/*.graphql
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/repository/amplify/API.service.ts
        docsFilePath: src/app/repository/amplify/graphql/
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: angular
        maxDepth: 10
extensions:
  amplify:
    version: 3
