projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/app/graphql/**/*.graphql
    excludes:
      - ./schema.graphql
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/providers/amplify/API.service.ts
        docsFilePath: src/app/graphql
        region: us-east-1
        apiId: kn33ywjqwfct5cwv345uobdr2e
        frontend: javascript
        framework: angular
        maxDepth: 10
extensions:
  amplify:
    version: 3
